const pairData: Pair[] = [
  {
    pairName: "WBTC.e-WETH.e",
    token0: "BTC",
    token1: "ETH",
    token0ID: "bitcoin",
    token1ID: "ethereum",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
  {
    pairName: "SOL-LUNA",
    token0: "SOL",
    token1: "LUNA",
    token0ID: "solana",
    token1ID: "terra-luna",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
  {
    pairName: "AVAX.e-ADA",
    token0: "AVAX",
    token1: "ADA",
    token0ID: "avalanche-2",
    token1ID: "cardano",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
  {
    pairName: "BNB-WETH.e",
    token0: "BNB",
    token1: "ETH",
    token0ID: "binancecoin",
    token1ID: "ethereum",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
  {
    pairName: "XRP-WBTC.e",
    token0: "XRP",
    token1: "BTC",
    token0ID: "ripple",
    token1ID: "bitcoin",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
  {
    pairName: "DOGE-SHIBA",
    token0: "DOGE",
    token1: "SHIBA",
    token0ID: "dogecoin",
    token1ID: "shiba-inu",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
  {
    pairName: "WETH.e-AVAX.e",
    token0: "ETH",
    token1: "AVAX",
    token0ID: "ethereum",
    token1ID: "avalanche-2",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
  {
    pairName: "SOL-BNB",
    token0: "SOL",
    token1: "BNB",
    token0ID: "solana",
    token1ID: "binancecoin",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
];

export { pairData };
