const pairDataArray: Pair[] = [
  {
    pairName: "WBTC.e-WETH.e",
    pairID: "bitcoin+ethereum",
    token0: "BTC",
    token1: "ETH",
    token0ID: "bitcoin",
    token1ID: "ethereum",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
  {
    pairName: "SOL-LUNA",
    pairID: "solana+terra-luna",
    token0: "SOL",
    token1: "LUNA",
    token0ID: "solana",
    token1ID: "terra-luna",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
  {
    pairName: "AVAX.e-ADA",
    pairID: "avalanche-2+cardano",
    token0: "AVAX",
    token1: "ADA",
    token0ID: "avalanche-2",
    token1ID: "cardano",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
  {
    pairName: "BNB-WETH.e",
    pairID: "binancecoin+ethereum",
    token0: "BNB",
    token1: "ETH",
    token0ID: "binancecoin",
    token1ID: "ethereum",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
  {
    pairName: "XRP-WBTC.e",
    pairID: "ripple+bitcoin",
    token0: "XRP",
    token1: "BTC",
    token0ID: "ripple",
    token1ID: "bitcoin",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
  {
    pairName: "DOGE-SHIBA",
    pairID: "dogecoin+shiba-inu",
    token0: "DOGE",
    token1: "SHIBA",
    token0ID: "dogecoin",
    token1ID: "shiba-inu",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
  {
    pairName: "WETH.e-AVAX.e",
    pairID: "ethereum+avalanche-2",
    token0: "ETH",
    token1: "AVAX",
    token0ID: "ethereum",
    token1ID: "avalanche-2",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
  {
    pairName: "SOL-BNB",
    pairID: "solana+binancecoin",
    token0: "SOL",
    token1: "BNB",
    token0ID: "solana",
    token1ID: "binancecoin",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
  {
    pairName: "WETH.e-SHIBA",
    pairID: "ethereum+shiba-inu",
    token0: "ETH",
    token1: "SHIBA",
    token0ID: "ethereum",
    token1ID: "shiba-inu",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
  {
    pairName: "GF-GALA",
    pairID: "guildfi+gala",
    token0: "GF",
    token1: "GALA",
    token0ID: "guildfi",
    token1ID: "gala",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
  {
    pairName: "NEAR-BAND",
    pairID: "near+band-protocol",
    token0: "NEAR",
    token1: "BAND",
    token0ID: "near",
    token1ID: "band-protocol",
    pairAddress: "https://snowtrace.io/",
    ratio: "50/50",
  },
];

export { pairDataArray };
